export const VERTICALS = {
  artisans: {
    id: 'artisans',
    label: 'Artisans BTP',
    icon: '🏗',
    color: '#2C6E49',
    colorLight: '#f0fdf4',
    entity: 'Artisan', entities: 'Artisans',
    project: 'Chantier', projects: 'Chantiers',
    skill: 'Corps de métier',
    territory: "Zone d'intervention",
    lead: 'Lead', leadsLabel: 'Leads',
    client: 'Client', clients: 'Clients',
    pipeline: 'Cycle de vente',
    packs: [
      { key: 'STARTER',  label: 'Concurrence', prix: '99,99 €',  color: '#1a71d4' },
      { key: 'PRO',      label: 'Exclusif',    prix: '149,99 €', color: '#7c3aed' },
      { key: 'BUSINESS', label: 'Agence Pro',  prix: '451,99 €', color: '#2C6E49' },
    ],
    kpis: [
      { label: 'Artisans actifs',    value: 142,          icon: 'fa-person-digging', trend: +12 },
      { label: 'Chantiers en cours', value: 38,           icon: 'fa-hard-hat',       trend: +5  },
      { label: 'Leads ce mois',      value: 94,           icon: 'fa-funnel',         trend: +18 },
      { label: 'CA encaissé',        value: '28 400 €',   icon: 'fa-euro-sign',      trend: +9  },
    ],
    leads: [
      { nom: 'Martin Dupont',  statut: 'interesse', ville: 'Paris',     metier: 'Plomberie'   },
      { nom: 'Sophie Bernard', statut: 'contacte',  ville: 'Lyon',      metier: 'Électricité' },
      { nom: 'Karim Bensalem', statut: 'converti',  ville: 'Marseille', metier: 'Maçonnerie'  },
      { nom: 'Julie Marchand', statut: 'nouveau',   ville: 'Bordeaux',  metier: 'Peinture'    },
      { nom: 'Thomas Laurent', statut: 'qualifie',  ville: 'Lille',     metier: 'Menuiserie'  },
    ],
    dossiers: [
      { ref: 'PRJ-2026-0041', client: 'Plomberie Sarl Renard', pack: 'Exclusif',    statut: 'ACTIF',                  prix: '149,99 €' },
      { ref: 'PRJ-2026-0042', client: 'Électro Pro Martin',    pack: 'Concurrence', statut: 'ACTIF',                  prix: '99,99 €'  },
      { ref: 'PRJ-2026-0043', client: 'Maçonnerie Bensalem',   pack: 'Agence Pro',  statut: 'EN_COURS_DE_SIGNATURE',  prix: '451,99 €' },
    ],
    activities: [
      { id: 1,  type: 'appel', titre: 'Appel de qualification',      contact: 'Martin Dupont',         date: '2026-06-28', heure: '09:00', statut: 'planifie',  note: 'Projet rénovation salle de bain' },
      { id: 2,  type: 'rdv',   titre: 'Visite de chantier',          contact: 'Karim Bensalem',        date: '2026-06-28', heure: '14:00', statut: 'planifie',  note: 'Marseille – maçonnerie façade' },
      { id: 3,  type: 'email', titre: 'Envoi du devis',              contact: 'Thomas Laurent',        date: '2026-06-27', heure: '16:30', statut: 'fait',      note: '' },
      { id: 4,  type: 'tache', titre: 'Préparer contrat Exclusif',   contact: 'Sophie Bernard',        date: '2026-06-27', heure: '11:00', statut: 'fait',      note: '' },
      { id: 5,  type: 'note',  titre: 'Note de suivi chantier',      contact: 'Plomberie Sarl Renard', date: '2026-06-27', heure: '10:00', statut: 'fait',      note: 'Avancement 60 %' },
      { id: 6,  type: 'appel', titre: 'Relance téléphonique',        contact: 'Julie Marchand',        date: '2026-06-26', heure: '15:00', statut: 'en_retard', note: 'Devis peinture sans réponse' },
      { id: 7,  type: 'rdv',   titre: 'RDV de signature',            contact: 'Sophie Bernard',        date: '2026-06-30', heure: '10:00', statut: 'planifie',  note: 'Contrat Exclusif 149,99 €/mois' },
      { id: 8,  type: 'email', titre: 'Confirmation de rendez-vous', contact: 'Julie Marchand',        date: '2026-06-28', heure: '08:30', statut: 'fait',      note: '' },
      { id: 9,  type: 'tache', titre: 'Relancer dossier en attente', contact: 'Électro Pro Martin',    date: '2026-06-25', heure: '09:00', statut: 'en_retard', note: '' },
      { id: 10, type: 'appel', titre: 'Bilan mensuel partenariat',   contact: 'Maçonnerie Bensalem',   date: '2026-06-30', heure: '16:00', statut: 'planifie',  note: '' },
    ],
  },

  immobilier: {
    id: 'immobilier',
    label: 'Immobilier',
    icon: '🏢',
    color: '#1a71d4',
    colorLight: '#eff6ff',
    entity: 'Mandataire', entities: 'Mandataires',
    project: 'Mandat', projects: 'Mandats',
    skill: 'Spécialité',
    territory: 'Secteur géographique',
    lead: 'Prospect', leadsLabel: 'Prospects',
    client: 'Acquéreur', clients: 'Acquéreurs',
    pipeline: "Cycle d'acquisition",
    packs: [
      { key: 'STARTER',  label: 'Starter',    prix: '99,99 €',  color: '#1a71d4' },
      { key: 'PRO',      label: 'Premium',    prix: '149,99 €', color: '#7c3aed' },
      { key: 'BUSINESS', label: 'Pro Agence', prix: '451,99 €', color: '#0e7490' },
    ],
    kpis: [
      { label: 'Mandataires actifs', value: 87,          icon: 'fa-building',     trend: +8  },
      { label: 'Mandats en cours',   value: 214,         icon: 'fa-file-contract',trend: +22 },
      { label: 'Prospects ce mois',  value: 61,          icon: 'fa-funnel',       trend: +14 },
      { label: 'Commissions',        value: '31 200 €',  icon: 'fa-euro-sign',    trend: +11 },
    ],
    leads: [
      { nom: 'Claire Fontaine', statut: 'interesse', ville: 'Paris',    metier: 'Résidentiel' },
      { nom: 'Marc Dubois',     statut: 'contacte',  ville: 'Lyon',     metier: 'Commercial'  },
      { nom: 'Amina Rachdi',    statut: 'converti',  ville: 'Nice',     metier: 'Luxe'        },
      { nom: 'Paul Lecomte',    statut: 'nouveau',   ville: 'Nantes',   metier: 'Neuf'        },
      { nom: 'Sandra Petit',    statut: 'qualifie',  ville: 'Bordeaux', metier: 'Location'    },
    ],
    dossiers: [
      { ref: 'IMM-2026-0018', client: 'Agence Horizon Immo',  pack: 'Premium',    statut: 'ACTIF',                 prix: '149,99 €' },
      { ref: 'IMM-2026-0019', client: 'Cabinet Dubois & Fils', pack: 'Starter',    statut: 'ACTIF',                 prix: '99,99 €'  },
      { ref: 'IMM-2026-0020', client: "Réseau Côte d'Azur",   pack: 'Pro Agence', statut: 'EN_COURS_DE_SIGNATURE', prix: '451,99 €' },
    ],
    activities: [
      { id: 1,  type: 'rdv',   titre: 'Visite bien immobilier',      contact: 'Claire Fontaine',    date: '2026-06-28', heure: '10:00', statut: 'planifie',  note: 'Appartement Paris 16ème' },
      { id: 2,  type: 'appel', titre: 'Appel acquéreur',             contact: 'Marc Dubois',        date: '2026-06-28', heure: '11:30', statut: 'planifie',  note: '' },
      { id: 3,  type: 'email', titre: 'Envoi estimation prix',       contact: 'Paul Lecomte',       date: '2026-06-27', heure: '14:00', statut: 'fait',      note: '' },
      { id: 4,  type: 'tache', titre: 'Préparer mandat exclusif',    contact: 'Amina Rachdi',       date: '2026-06-27', heure: '16:00', statut: 'fait',      note: '' },
      { id: 5,  type: 'note',  titre: 'Visite – impression positive',contact: 'Claire Fontaine',    date: '2026-06-27', heure: '11:00', statut: 'fait',      note: 'Très intéressée, rappeler lundi' },
      { id: 6,  type: 'appel', titre: 'Relance prospect froid',      contact: 'Paul Lecomte',       date: '2026-06-26', heure: '15:30', statut: 'en_retard', note: 'Pas de réponse depuis 5 jours' },
      { id: 7,  type: 'rdv',   titre: 'RDV chez le notaire',         contact: 'Sandra Petit',       date: '2026-06-30', heure: '09:00', statut: 'planifie',  note: 'Compromis de vente' },
      { id: 8,  type: 'email', titre: 'Compte-rendu de visite',      contact: 'Marc Dubois',        date: '2026-06-28', heure: '09:00', statut: 'fait',      note: '' },
      { id: 9,  type: 'tache', titre: 'Mettre à jour fiche bien',    contact: "Réseau Côte d'Azur", date: '2026-06-25', heure: '17:00', statut: 'en_retard', note: '' },
      { id: 10, type: 'rdv',   titre: 'Signature compromis',         contact: 'Amina Rachdi',       date: '2026-07-01', heure: '14:00', statut: 'planifie',  note: 'Bien luxe Nice Cimiez' },
    ],
  },

  recrutement: {
    id: 'recrutement',
    label: 'Recrutement',
    icon: '💼',
    color: '#7c3aed',
    colorLight: '#f5f3ff',
    entity: 'Consultant', entities: 'Consultants',
    project: 'Mission', projects: 'Missions',
    skill: 'Profil recherché',
    territory: 'Zone de déplacement',
    lead: 'Candidat', leadsLabel: 'Candidats',
    client: 'Entreprise cliente', clients: 'Entreprises',
    pipeline: 'Cycle de placement',
    packs: [
      { key: 'STARTER',  label: 'Essentiel',  prix: '99,99 €',  color: '#7c3aed' },
      { key: 'PRO',      label: 'Business',   prix: '149,99 €', color: '#6d28d9' },
      { key: 'BUSINESS', label: 'Enterprise', prix: '451,99 €', color: '#4c1d95' },
    ],
    kpis: [
      { label: 'Consultants actifs', value: 56,          icon: 'fa-user-tie',   trend: +6  },
      { label: 'Missions en cours',  value: 103,         icon: 'fa-briefcase',  trend: +17 },
      { label: 'Candidats ce mois',  value: 248,         icon: 'fa-funnel',     trend: +31 },
      { label: 'Honoraires',         value: '19 800 €',  icon: 'fa-euro-sign',  trend: +14 },
    ],
    leads: [
      { nom: 'Alexis Morel',  statut: 'interesse', ville: 'Paris',      metier: 'Dev Senior'     },
      { nom: 'Fatima Benali', statut: 'contacte',  ville: 'Lyon',       metier: 'Chef de projet' },
      { nom: 'Hugo Garnier',  statut: 'converti',  ville: 'Toulouse',   metier: 'Data Engineer'  },
      { nom: 'Léa Rousseau',  statut: 'nouveau',   ville: 'Nantes',     metier: 'UX Designer'    },
      { nom: 'Romain Blanc',  statut: 'qualifie',  ville: 'Strasbourg', metier: 'DevOps'         },
    ],
    dossiers: [
      { ref: 'REC-2026-0033', client: 'TechCorp Solutions',  pack: 'Business',   statut: 'ACTIF',                 prix: '149,99 €' },
      { ref: 'REC-2026-0034', client: 'StartupHub Paris',    pack: 'Essentiel',  statut: 'ACTIF',                 prix: '99,99 €'  },
      { ref: 'REC-2026-0035', client: 'Groupe Industria RH', pack: 'Enterprise', statut: 'EN_COURS_DE_SIGNATURE', prix: '451,99 €' },
    ],
    activities: [
      { id: 1,  type: 'appel', titre: 'Entretien téléphonique',   contact: 'Alexis Morel',       date: '2026-06-28', heure: '09:30', statut: 'planifie',  note: 'Poste Dev Senior – TechCorp' },
      { id: 2,  type: 'rdv',   titre: 'Entretien physique',       contact: 'Hugo Garnier',       date: '2026-06-28', heure: '14:00', statut: 'planifie',  note: 'Data Engineer – mission 6 mois' },
      { id: 3,  type: 'email', titre: 'Envoi profil candidat',    contact: 'Fatima Benali',      date: '2026-06-27', heure: '10:30', statut: 'fait',      note: '' },
      { id: 4,  type: 'tache', titre: 'Vérifier les références',  contact: 'Romain Blanc',       date: '2026-06-27', heure: '15:00', statut: 'fait',      note: '' },
      { id: 5,  type: 'note',  titre: 'Retour client positif',    contact: 'TechCorp Solutions', date: '2026-06-27', heure: '17:00', statut: 'fait',      note: 'Très intéressés par Hugo G.' },
      { id: 6,  type: 'appel', titre: 'Appel de présélection',    contact: 'Léa Rousseau',       date: '2026-06-26', heure: '11:00', statut: 'en_retard', note: 'Poste UX Designer – StartupHub' },
      { id: 7,  type: 'rdv',   titre: 'Test technique',           contact: 'Alexis Morel',       date: '2026-06-30', heure: '09:00', statut: 'planifie',  note: 'Remote – 2h de codage' },
      { id: 8,  type: 'email', titre: 'Proposition salariale',    contact: 'Hugo Garnier',       date: '2026-06-28', heure: '08:00', statut: 'fait',      note: '' },
      { id: 9,  type: 'tache', titre: 'Préparer dossier mission', contact: 'StartupHub Paris',   date: '2026-06-25', heure: '10:00', statut: 'en_retard', note: '' },
      { id: 10, type: 'appel', titre: 'Suivi placement candidat', contact: 'Groupe Industria RH',date: '2026-06-30', heure: '15:00', statut: 'planifie',  note: '' },
    ],
  },

  formation: {
    id: 'formation',
    label: 'Formation',
    icon: '🎓',
    color: '#f59e0b',
    colorLight: '#fffbeb',
    entity: 'Formateur', entities: 'Formateurs',
    project: 'Session', projects: 'Sessions',
    skill: 'Filière',
    territory: "Zone d'intervention",
    lead: 'Apprenant', leadsLabel: 'Apprenants',
    client: 'Organisme', clients: 'Organismes',
    pipeline: 'Cycle de formation',
    packs: [
      { key: 'STARTER',  label: 'Solo',        prix: '99,99 €',  color: '#f59e0b' },
      { key: 'PRO',      label: 'Groupe',      prix: '149,99 €', color: '#d97706' },
      { key: 'BUSINESS', label: 'Institution', prix: '451,99 €', color: '#b45309' },
    ],
    kpis: [
      { label: 'Formateurs actifs',     value: 73,          icon: 'fa-chalkboard-user', trend: +10 },
      { label: 'Sessions en cours',     value: 29,          icon: 'fa-graduation-cap',  trend: +4  },
      { label: 'Apprenants ce mois',    value: 412,         icon: 'fa-funnel',          trend: +26 },
      { label: 'Formations encaissées', value: '22 500 €',  icon: 'fa-euro-sign',       trend: +7  },
    ],
    leads: [
      { nom: 'Emma Durand',   statut: 'interesse', ville: 'Paris',       metier: 'Digital Marketing'  },
      { nom: 'Luc Ferrand',   statut: 'contacte',  ville: 'Lyon',        metier: 'Comptabilité'       },
      { nom: 'Yasmine Kamel', statut: 'converti',  ville: 'Toulouse',    metier: 'Développement Web'  },
      { nom: 'Pierre Aubert', statut: 'nouveau',   ville: 'Rennes',      metier: 'Management'         },
      { nom: 'Inès Lebrun',   statut: 'qualifie',  ville: 'Montpellier', metier: 'Langues'            },
    ],
    dossiers: [
      { ref: 'FOR-2026-0022', client: 'CFA Numérique Pro',      pack: 'Groupe',      statut: 'ACTIF',                 prix: '149,99 €' },
      { ref: 'FOR-2026-0023', client: 'Institut Formation 3.0', pack: 'Solo',        statut: 'ACTIF',                 prix: '99,99 €'  },
      { ref: 'FOR-2026-0024', client: 'Université Ouverte',     pack: 'Institution', statut: 'EN_COURS_DE_SIGNATURE', prix: '451,99 €' },
    ],
    activities: [
      { id: 1,  type: 'appel', titre: 'Session info inscription',     contact: 'Emma Durand',            date: '2026-06-28', heure: '10:00', statut: 'planifie',  note: 'Digital Marketing – promo juillet' },
      { id: 2,  type: 'rdv',   titre: 'Entretien pédagogique',        contact: 'Pierre Aubert',          date: '2026-06-28', heure: '14:30', statut: 'planifie',  note: 'Management – évaluation pré-formation' },
      { id: 3,  type: 'email', titre: 'Envoi programme de formation', contact: 'Luc Ferrand',            date: '2026-06-27', heure: '09:00', statut: 'fait',      note: '' },
      { id: 4,  type: 'tache', titre: 'Préparer convention OPCO',     contact: 'CFA Numérique Pro',      date: '2026-06-27', heure: '14:00', statut: 'fait',      note: '' },
      { id: 5,  type: 'note',  titre: 'Bilan session Comptabilité',   contact: 'Institut Formation 3.0', date: '2026-06-27', heure: '16:30', statut: 'fait',      note: 'Taux de satisfaction 94 %' },
      { id: 6,  type: 'appel', titre: 'Relance dossier financement',  contact: 'Inès Lebrun',            date: '2026-06-26', heure: '11:30', statut: 'en_retard', note: 'CPF en attente validation' },
      { id: 7,  type: 'rdv',   titre: 'Ouverture de session',         contact: 'Yasmine Kamel',          date: '2026-06-30', heure: '09:00', statut: 'planifie',  note: 'Développement Web – groupe de 8' },
      { id: 8,  type: 'email', titre: 'Confirmation inscription',     contact: 'Emma Durand',            date: '2026-06-28', heure: '08:00', statut: 'fait',      note: '' },
      { id: 9,  type: 'tache', titre: "Envoyer attestation formation",contact: 'Université Ouverte',     date: '2026-06-25', heure: '10:00', statut: 'en_retard', note: '' },
      { id: 10, type: 'appel', titre: 'Suivi satisfaction apprenants',contact: 'Luc Ferrand',            date: '2026-06-30', heure: '11:00', statut: 'planifie',  note: '' },
    ],
  },
}

export const VERTICAL_LIST = Object.values(VERTICALS)
